### ISSUE TITLE
Decadal white paper

### ISSUE THREAD

**Issue by michaelaye** [planetarysoftware/TSC#102]
I really think the decadal needs a software infrastructure white paper (WP), layout out what we think is needed to support planetary science software-wise, but I'm not sure it would need to talk about PDS, as they are doing already a WP, I believe?

I'm brainstorming what would need to get into such a WP and was hoping to get section authors writing 0.5 to 1 page for their section and we glue it all together in the remaining 2 months?

Here's what I came up with so far:

* ISIS
  * I heard that USGS needs to go through interval review for being even a co-signer? I would not sign up to lead this if I need to put the pen down 2 weeks in advance, so not sure how to handle this.
* cloud-computing of PDS data? (it get's more traction recently, so it should be discussed i think, but have no personal experience with it
* standardized Python modules (aka planetarypy, with constants etc.) (maybe at least discussing easier PDS data access?)
* ASP

what else is a corner stone of planetary software these days, QGIS maybe?

**Comment by rbeyer** [comment]
Seems like you're already in the weeds with specifics.  You say "software infrastructure white paper" but what about it, specifically?

What is our one-line (or one-para) summary that we would want the Decadal to do?  That's ultimately the point of these white papers: and that is to convince the Decadal Survey to recommend something to NASA to do in the next decade.  Do we want them to recommend funding or set policy?  What is it that you want NASA to do?  Then we work backwards from there.

**Comment by michaelaye** [comment]
Weeks? Weeds?
I don't agree it has to be one message but I agree it might be practical to start with the list of things we want to push and work the motivations back from there. 
I think we can come up with a set of recommendations similar to what has been done in the ML for PS white paper, where at the end a whole 10 recommendations were given that are very wide ranging, from more funding, updated language of solicitations to as simple as encouraging the considerations of ML application when discussing the future of PDS.

I can have a go at putting some recommendations into a document. Most likely they will stimulate a lot of discussions especially when some party thinks the recommendation is just fairy eyed dreaming or disadvantageous to other programs or not sufficiently neutral.

**Comment by AndrewAnnex** [comment]
I agree with Ross here, it’s sort of like building an STM, we need the high level motivating question. It could just be “we think planetary science software should be more open source” or “we think nasa is not giving software and tool development the focus it deserves” but that would help focus the discussions. Every white paper I have read or co-signed had a clearly identifiable point to it. 

-Andrew Annex

**Comment by michaelaye** [comment]
I feel like "we think nasa is not giving X and Y the focus it deserves” is the reason why a white paper is being written at all and am not sure how such a statement helps the discussion? In other words, that seems to be an implied motivation for thinking about a WP at all and I implied it. but then?

**Comment by michaelaye** [comment]
Link to Arfon's Astrophysics Decadal WP: https://arxiv.org/abs/1907.06981

ML for PS for PS decadal: https://arxiv.org/abs/2007.15129 (I especially the bullet list of recommendations at the end of the doc)

**Comment by AndrewAnnex** [comment]
I guess we can close this now?
