### ISSUE TITLE
PlanetaryPy Review

### ISSUE THREAD

**Issue by rbeyer** [planetarysoftware/TSC#112]
As a member of both the TSC and the PlanetaryPy TC, I note that the PlanetaryPy TLP Incubation Issue, #108, indicates that the PlanetaryPy project has nominally passed all of its criteria, and I would like to request a review, as indicated in [Section 5 of the Lifecycle Document](https://github.com/planetarysoftware/TSC/blob/master/Lifecycle.md#5-tsc-review---issue-created).  We should probably create a template for this kind of Issue, also.

Given the stated requirements, and the fact that there are only two members of the TSC that can possibly carry out this review, they are the stuckees, and I have assigned them to this Issue: please do what Section 5 says, and enter your evaluations in this Issue so that we might be able to have a vote at the Nov meeting.

**Comment by victoronline** [comment]
As a member of the TSC not in conflict (not members of its TLP, nor its mentors) with the PlanetaryPy TLP, I've reviewed the state of the project and have determined that the project has met the criteria listed in Incubation Issue #108.
