### ISSUE TITLE
ISIS Incubation Status

### ISSUE THREAD

**Issue by victoronline** [planetarysoftware/TSC#113]
## 

This  has been accepted under incubation. This issue documents its current status. The incubation process is described in the [Lifecycle document](https://github.com/planetarysoftware/TSC/blob/master/Lifecycle.md).

### Application
The project's application document can be found [here](https://github.com/planetarysoftware/TSC/blob/master/Applications/ISIS.md).

### Mentor
This project is being mentored through the incubation process by @victoronline 

### Participation
 - [x] At least three members participating. 

Current membership is listed [here](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/Members.md). Additionally, meeting attendance is listed in the meeting [notes](https://github.com/USGS-Astrogeology/ISIS_TC/tree/master/meetings).

### Transparency
 - [x] All decisions and the decision making process are publicly documented.

The decision making process is outlined in the [charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md). Decisions are documented in the meeting [notes](https://github.com/USGS-Astrogeology/ISIS_TC/tree/master/meetings).

### Charter
 - [x] The ISIS TLP has a public charter

The charter can be found [here](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md).

### Code of Conduct
 - [x] The ISIS TLP uses the Planetary Software TSC code of conduct

### Contributing Guidelines
 - [x] The ISIS TLP's contributing guidelines can be found [here](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md).

**Comment by victoronline** [comment]
A lingering issue that may have already been resolved but I can't seem to find documentation regarding it is the licensing issue with the (Kakadu)[https://kakadusoftware.com/] library for JPEG2000 support. We should probably just state that we are making an exception to the acceptable licenses.

**Comment by victoronline** [comment]
All 5 checkmarks have been checked but we have to resolve the licensing issue. It will be discussed at the next ISIS TC meeting.

**Comment by victoronline** [comment]
The code of conduct is being discussed. Will check off when its complete.

**Comment by victoronline** [comment]
Do we have to revisit the the decision making process outlined in the charter?

**Comment by jlaura** [comment]
@victoronline Can you be more specific? I do not know what you are referring to.

**Comment by victoronline** [comment]
My apologies, I should've worded that in a different way. 

I was just comparing this incubation issue to the PlanetaryPy incubation issue, specifically where project decision-making is defined. For PlanetaryPy, their decision-making process is outlined in their charter. For ISIS, its not as straight-forward.

The TSC requirement is that all "Decisions must be made publicly through a documented public process managed by each TLP TC or TLWG."

This is where the ISIS joint governance model (governed by ASC and the ISIS TC) makes things a bit tricky and can lead to confusion. The way this joint governance model is setup, it appears that the decisions for the project are made by ASC with support from ISIS TC. Since the decision-making falls on the ASC side, we should make sure the project clearly meets the requirement mentioned above.

The decisions (outcomes) made by ASC for the project are public. That's easy. However, can we say that the decision process used by ASC for the ISIS project is a public process?

**Comment by victoronline** [comment]
Am I reading that wrong? Does "Decisions must be made publicly through a documented public process managed by each TLP TC or TLWG." just mean TC decisions or project decisions?

**Comment by jlaura** [comment]
It looks to me like ISIS and PlanetaryPy have largely identical governance models. They are both adopting processes inline with this organization. They might have different contribution models. Unless those models are in conflict with being transparent and open source, I do not think that we can do anything other than maybe make suggestions about the contribution models. The contribution model is really up to the contributors on the project. They can select whatever works for that community.

I do believe the ISIS application needs to be updated to indicate that the ISIS TC is the body that is making process decision for the project. This is not a joint governance model.

**Comment by victoronline** [comment]
I'm just trying to make sure our requirements are met and trying to be somewhat of a "devil's advocate" since this is one of the more complicated project applications.

I'm specifically talking about the TSC requirement that all "Decisions must be made publicly through a documented public process managed by each TLP TC or TLWG."  Does this mean decisions internal to the TC or for the project? It sounds like this is referring to decisions about the project. Thoughts?

In regards to governance, if this is not a joint governance model, then that language needs to be changed in a few places in the application, including, [governance](https://github.com/planetarysoftware/TSC/blob/master/Applications/ISIS.md#governance), [history-outlook](https://github.com/planetarysoftware/TSC/blob/master/Applications/ISIS.md#history--outlook), and [scope](https://github.com/planetarysoftware/TSC/blob/master/Applications/ISIS.md#scope).

**Comment by victoronline** [comment]
Updated the issue template to "check-off" the items that were previously missing but have now been updated. Will discuss in meeting today to hopefully, graduate from incubation.

**Comment by victoronline** [comment]
A vote on graduation from incubation was tabled until next meeting. 

There remains a need for clarity around the language that describes the Governance/Ownership models in the application vs. the charter. This is due to the evolution of the project models over time. However, the state of Governance/Ownership models that will be considered in the vote needs to be clearly identified in project's documentation at the time a vote is taken. If mentioned in other project documentation, the same language should be referenced as to not be in conflict. 

We will try to nail this down at next ISIS_TC meeting.

**Comment by victoronline** [comment]
The need for clarity around governance language was resolved by updating the ISIS application to refer to the governance language in the ISIS charter.  See #123 

Since the language now exists only in the charter, this issue is ready to move on to a vote to graduate to Top-Level Project(TLP).  

To adhere to the Lifecycle document, I'm going to request this issue be approved by at least two members, even though verbal approval was given by more than two members via meeting discussion. 

Once the two reviews are completed, I will create the PR to formalize the vote to graduate out of Incubation to TLP.

 \- Edit: Added link to app change PR. Jesse

**Comment by rbeyer** [comment]
There's no GitHub mechanism for "approving" an Issue, but you certainly have my approval.  It is the PR that you will make that will only need 2 approvals, since we held a voice vote at the meeting today.

**Comment by victoronline** [comment]
Thanks Ross. I was definitely thinking about the PR. The lifecycle doc requires 2 reviewers for the issue...but we've done that. Creating the PR.

**Comment by victoronline** [comment]
PR [#126 ](https://github.com/planetarysoftware/TSC/pull/126) was created to close out this issue.
