### ISSUE TITLE
Brochure for TSC

### ISSUE THREAD

**Issue by AndrewAnnex** [planetarysoftware/TSC#120]
reply with salespitches/elevator pitch points for why the TSC is cool/can help your project out and how. share this with folks we are interested in having join us! once we collect a good list I can compile a pr with a new markdown file.

**Comment by jessemapel** [comment]
As the Integrated Software for Imagers and Spectrometers software package has moved to open source, going through the Planetary Software package application process has helped us build a path for new contributors. As a very large package that was developed internally by a single team, we had (and still have some) systems and processes that we're informally communicated and managed. Going through the application process has helped us examine what we do from a different perspective. It has pushed us to re-evaluate many things and make them better for contributors in the community. It has also created a way for other contributors to raise concerns and discuss how the contribution process can be improved.

**Comment by jlaura** [comment]
See: https://www.hou.usra.edu/meetings/planetdata2021/pdf/7029.pdf

**Comment by AndrewAnnex** [comment]
closing this issue thanks to the recent PDW/PSIDA talk and abstract https://www.youtube.com/watch?v=IYmFVtScKXk
https://www.hou.usra.edu/meetings/planetdata2021/pdf/7029.pdf
