### ISSUE TITLE
Base Policies Migration

### ISSUE THREAD

**Issue by jlaura** [planetarysoftware/TSC#18]
We need to get the documents inside of the BasePolicies directory updated for the TSC.

**Comment by rbeyer** [comment]
Yeah, I'm actually confused about how to go about it.  There are all of the very old documents in that directory.  There's an echo of some of that in the main https://github.com/planetarysoftware/TSC/blob/master/WORKING_GROUPS.md file and then the https://github.com/planetarysoftware/TSC/blob/master/Applications/Template.md also talks about working groups.

So I'm not quite sure where to start.

**Comment by rbeyer** [comment]
Having this unresolved is going to impede any forward motion that the PlanetaryPy TC might make, hopefully someone who is more knowledgeable can address this before the next TSC meeting.

**Comment by rbeyer** [comment]
Okay, I'm sorry for being so confused, but:

All of the documents in the new [BootStrap-Policies](https://github.com/planetarysoftware/TSC/tree/master/Bootstrap-Policies) directory now talk about being relevant to working groups, which is fine, but the first sentence in that directory's readme talks about a 'TC.'  Are the documents in this directory meant to apply to bootstrapping of working groups *and* technical committees?  If not, then we need documents for bootstrapping a technical committee, too, right?

Also, is [this Template](https://github.com/planetarysoftware/TSC/blob/master/Applications/Template.md) an application template for a 'Top Level Project' or a 'Top Level Working Group'?

**Comment by michaelaye** [comment]
link to the template broken, @rbeyer ?

**Comment by rbeyer** [comment]
Oh, relative links work in Markdown files, but not in these comment boxes in Issues and PRs, bummer.

**Comment by rbeyer** [comment]
#66 might resolve this Issue.

**Comment by jessemapel** [comment]
@rbeyer I would say so
