### ISSUE TITLE
Add badge to the appropriate docs

### ISSUE THREAD

**Issue by jlaura** [planetarysoftware/TSC#20]
The UV badge should be added to the appropriate place so that other projects can go ahead and pull this.

**Comment by AndrewAnnex** [comment]
oops... will get to this before next meeting

**Comment by rbeyer** [comment]
Can someone either accurately define 'appropriate place' so that someone can do this and close it, or can one of you that already knows just do this, and close?  Thanks.

**Comment by jessemapel** [comment]
Fixed by #45
