### ISSUE TITLE
Chat space?

### ISSUE THREAD

**Issue by michaelaye** [planetarysoftware/TSC#23]
I'm interested in having a designated chat space for little questions or communications in a group forum that doesn't clog anyones email.
I guess this could be a private channel inside the OpenPlanetary slack if people are using that regularly?
Anybody else interested?

**Comment by rbeyer** [comment]
Is there a need that GitHub Issues aren't satisfying for your use case?  I don't have a problem getting e-mails, but I don't have a problem with a Slack channel either (which I'd just end up having send me e-mails, since I don't visit Slack regularly).

**Comment by jessemapel** [comment]
I am fine with anything, but it needs to be public.

**Comment by jlaura** [comment]
I honestly don't have the bandwidth for yet another chat tool. Email is painful, but all in one place which is appreciated. Whatever works, I'm just not likely to register for another chat place.

**Comment by michaelaye** [comment]
Ok, pity. I would have thought that it would have created a tighter knit of the group, but then GH issues it is.

**Comment by jlaura** [comment]
I'm not saying don't do it. I am just saying that it needs to have direct to email / email response or be on an existing platform that we all use. Also, just because I am a stick in the mud for online chat communities doesn't mean you all shouldn't use one!

**Comment by rbeyer** [comment]
So you can get Slack to send you e-mail (just like I have AstroDiscuss do), but Michael hasn't clearly stated the use case he's after, which I'd like to understand better, so we can make a good decision.

**Comment by michaelaye** [comment]
My use case would be quick exchanges like “did you do this already” or “who is working on it” but apparently people are fine with this cluttering GitHub so I don’t want to insist on a chat.

**Comment by michaelaye** [comment]
actually, my issue is less cluttering, after all we decided to organize ourselves around GH, but my issue is availability of this as a fast communication channel.
Deciding on a new GH issue and submitting it, or finding the issue where a certain communication thread is happening takes more time than just “shouting” into a chat room, in my opinion. YMMV.

**Comment by rbeyer** [comment]
I think that at our last meeting (August 2019, but not in the notes), we talked about this, and decided that using the Github team channels for this was what we'd try doing when someone has this need.  If that's your understanding, too, @michaelaye, then can we close this?

**Comment by michaelaye** [comment]
Yes!
