### ISSUE TITLE
Project e-mails?

### ISSUE THREAD

**Issue by rbeyer** [planetarysoftware/TSC#26]
In reading through the Code of Conduct I just PRed, and the Node.js Moderation Policy, there's a need for some project-level e-mail addresses.  For the Moderation Policy, they have a report@node.js that is clearly a list that sends out to the Mod team.  Do we need something like this, or is there some other mechanism that we can use?  If we need it, do we just make a Gmail account?  Do we make a Google Group?  Thoughts?  Ideas?

**Comment by michaelaye** [comment]
i don't have a clear picture of what we would be moderating? The text in GitHub issues? Note also that GitHub Orgs have a feature called teams with their own chat-boards. So we could have a team of moderators and other teams as needed?

**Comment by michaelaye** [comment]
These teams can be addressed via a single @tsc-members for example, and the good thing/idea with team discussions is that their discussion board can serve for discussions that are crossing projects or GH issues. https://help.github.com/en/articles/about-team-discussions

**Comment by jlaura** [comment]
I am going to checkout: https://gaggle.email/

Also, whatever looks good, we need to go ahead and update the on-boarding documents.

**Comment by jlaura** [comment]
I have set up a group email at `planetary-software@gaggle.email`. If you would like to be added to the group that gets emails from that address please ping me with the email address I should register.

We can have up to 20 people before we would need to upgrade from the free version.

**Comment by michaelaye** [comment]
On Aug 15, 2019, 11:05 -0600, jlaura <notifications@github.com>, wrote:
> I have set up a group email at planetary-software@gaggle.email. If you would like to be added to the group that gets emails from that address please ping me with the email address I should register.
>
I was about to set up a hacking scheme to break into the network of USGS to be able to ping you a message (it was always fun to message unsuspecting users in the unix pools 25 years ago), but I hope email is okay, with federal laws and so...? ;)

kmichael.aye@gmail.com would be good for the group email.

Thanks!
Michael
