### ISSUE TITLE
Terminology: "top level" or "core" working groups?

### ISSUE THREAD

**Issue by michaelaye** [planetarysoftware/TSC#27]
the main [readme](https://github.com/planetarysoftware/TSC#top-level-wgs-and-tlps)'s section calls it Top Level WGs, but [the working groups document](https://github.com/planetarysoftware/TSC/blob/master/WORKING_GROUPS.md) calls it core working group? I guess we have to settle on a term?

**Comment by jessemapel** [comment]
I prefer top level because working groups and projects can have working groups under-neath them. For example, the ISIS project will probably have a testing working group under it.

**Comment by rbeyer** [comment]
We decided in the meeting that the answer is 'top level.'

**Comment by michaelaye** [comment]
i just keep this issue to keep track of it.

**Comment by jessemapel** [comment]
Let's keep this open until we got the documents scrubbed for this language.

**Comment by rbeyer** [comment]
Okay, can we get a listing of documents where this is needed, so we know when we're done?

**Comment by rbeyer** [comment]
So I think #57 completes this, right?  Any others?

**Comment by michaelaye** [comment]
only other docs that have the word "core" are meeting notes, so. should be. good.
