### ISSUE TITLE
working group bootstrap governance 

### ISSUE THREAD

**Issue by michaelaye** [planetarysoftware/TSC#28]
The end of the [bootstrap governence](https://github.com/planetarysoftware/TSC/blob/master/WORKING_GROUPS.md#bootstrap-governance) has a few issues:

* Moderation Policy: Should it link to the TSC's version?
* Code of conduct: 
> The [Planetary Software Organization][] applies to this WG.
something missing here? Or simply link to our code of conduct?
* The end of the bootstrap governance links to ASC's CoC, is that meant as example? Or should it be removed?
* The moderation policy is linked at the very end, should that link? be in the section above CoC? I can make the PR if we agree on which way to go.

**Comment by jessemapel** [comment]
>     * Moderation Policy: Should it link to the TSC's version?
I think that's a good idea.

>     * Code of conduct:
> > The [Planetary Software Organization][] applies to this WG.
> something missing here? Or simply link to our code of conduct?

I think this is bundled up with #25 and needs to be updated to link to our current code of conduct

>     * The end of the bootstrap governance links to ASC's CoC, is that meant as example? Or should it be removed?
>     * The moderation policy is linked at the very end, should that link? be in the section above CoC? I can make the PR if we agree on which way to go.

I think both of these links should go

I'm going to put up a PR for this.
