### ISSUE TITLE
July Meeting date

### ISSUE THREAD

**Issue by jessemapel** [planetarysoftware/TSC#3]
We didn't decide on a meeting time for July. I'd suggest the 9th or the 16th.

**Comment by jlaura** [comment]
9th is significantly better here. I believe I have family in town the 16th. Having said that I don't need to be in attendance so whatever works for the group is cool.

**Comment by rbeyer** [comment]
9th is better, here, too.

**Comment by victoronline** [comment]
9th works for me.

**Comment by jessemapel** [comment]
@michaelaye @SgStapleton @AndrewAnnex Does the 9th work for you?

**Comment by michaelaye** [comment]
yes, 9th also better than 16th. I'm back in Flagstaff on 16th. ;)

**Comment by SgStapleton** [comment]
I will have family in town around the 9th, but I can plan on calling in to the meeting no problem!

**Comment by rbeyer** [comment]
That's a majority, next meeting will be on the 9th.

**Comment by AndrewAnnex** [comment]
Yep 9th should work for me, was busy 

-Andrew Annex
