### ISSUE TITLE
Emphasizing collaboration

### ISSUE THREAD

**Issue by jessemapel** [planetarysoftware/TSC#39]
The current documentation is very prescriptive and may come off as dictatorial. The real strength of this group is the ability to share lessons learned and distribute knowledge throughout the community. To me, that is a collaborative organization. How can we present things as more collaborative?

Part of this came up during the missions statement discussion and I'm finding myself coming back to that. The mission statement doesn't say anything about how people can contribute back. Does specifying that impose too much work on people who just want help getting their software governance in order?

**Comment by jessemapel** [comment]
The path forward on this is two-fold.

1. We need to always be aware of this and be careful with how we work documents
1. Writing some simple "stories" that describe how the TSC can help projects that it is stewarding or advising.

**Comment by victoronline** [comment]
I'm currently working on changes for this. The "stories" will need to be polished a bit. We can replace the "stories" with actual examples when they become available.

**Comment by jessemapel** [comment]
I haven't gotten to any of this yet. @victoronline Can you put up a PR tomorrow with your changes so far?

**Comment by victoronline** [comment]
Jesse, I haven't opened a PR yet because I've been super busy as well this month. But I will do so with my changes so far.

**Comment by rbeyer** [comment]
@victoronline, you took the action to review the state of this issue and decide whether we can close. If not, recommend specific actions here.

**Comment by victoronline** [comment]
Created a PR with some changes in reference to language to mention ownership. Maybe mentioning ownership in more specific terms, will make the language a tad bit less "scary" for existing projects. We still have to add "stories" though.

**Comment by victoronline** [comment]
Recreating PR with just my changes. I thought I had an updated fork. Sorry folks.

**Comment by rbeyer** [comment]
Looks like this issue got focused down to a PR, but I'm not sure which one it was connected to.  Since its been more than a year since the last comment here, I'm thinking we can close?

**Comment by victoronline** [comment]
I agree. I think if we want to circle back to it, we should create another issue at that time.

**Comment by victoronline** [comment]
Closing issue after discussion in today's meeting.
