### ISSUE TITLE
Aligning our naming of documents and folders

### ISSUE THREAD

**Issue by michaelaye** [planetarysoftware/TSC#40]
As an image analyzer my visual cortex is quite disturbed by the volatility of our naming rules for documents and folders. We have all capital documents, we have all lower case folders, we have CamelCase folders, we have underscore and hyphen separated documents. 
Can we please please decide on one style? 🙏 I'm happy to perform the required changes throughout the whole repo, using my editor's refactoring tools. I'm guessing though that all PRs should be done at that point b/c filenames would change.

**Comment by jessemapel** [comment]
I am partial to upper camel case with hyphens. I.E. Moderation-Policy.md
