### ISSUE TITLE
organization ownership

### ISSUE THREAD

**Issue by rbeyer** [planetarysoftware/TSC#55]
I note that our planetarysoftware GitHub organization has only one 'owner' and a bunch of 'members' (because that's just how it was set up).  This doesn't particularly bother me, and hasn't been any kind of problem, but has a single-point-failure vibe to me.

Should more of the TSC be 'owners' of the GitHub organization?

And if so, how many?

I don't know that every TSC member needs to be an 'owner' (but we could, that could certainly be a policy).  Maybe at least three of us (since that's the minimum TSC membership)?

**Comment by jessemapel** [comment]
I think everyone on the TSC should have ownership.

**Comment by rbeyer** [comment]
Everyone is now an Owner.
