### ISSUE TITLE
Do we need another document describing the process of creating a TC?

### ISSUE THREAD

**Issue by michaelaye** [planetarysoftware/TSC#64]
Or should this be added to existing documents?

I'm not only interested in seeing a paragraph somewhere explaining to peeps why one needs a TC  for joining the TSC as a TLP, but also a bulleted lists of something like this, concerning how we technically do it:

* clone the TSC repo (or copy everything in this sub-folder? )
* delete this documents as not required for TC (eg no TLP inside a project's TC, right? But working groups could/should happen for a project.)
* Text replace <project> with the project's name etc...

**Comment by jessemapel** [comment]
I think we definitely do. I'm kind of trying to figure out what we're going to do as we go with ISIS on this front.

**Comment by rbeyer** [comment]
I'm noodling on this over the weekend for TLPs and TLWGs, and will have a PR soonish (depends on my weekend).

In the meantime: I have a questions:

How many for a TC?  In some of the documents we say 3, in others we say 5.  I'm thinking of using this sentence:

> A TC should have at least 3 initial members to start the work and
> get the application submitted to the Planetary Software TSC, but
> it will need 5 members in order to graduate from Incubation.

Discuss.

**Comment by rbeyer** [comment]
#66 is a first pass at resolving this issue.

**Comment by jessemapel** [comment]
@rbeyer I'm inclined to say 3. Most of the software we'll be working with will have a relatively small user base, so the lower bar makes sense.

**Comment by rbeyer** [comment]
Okay, I've updated the language in the PR for 3 members of the TC to 'graduate.'

**Comment by rbeyer** [comment]
I think #66 dealt with this, Michael, if you concur, please close this Issue.
