### ISSUE TITLE
LPSC 2020 OpenPlanetary Data Cafe

### ISSUE THREAD

**Issue by rbeyer** [planetarysoftware/TSC#74]
At EPSC / DPS, the OpenPlanetary folks indicated that they may not be able to make it to LPSC, but would be very happy to support an OpenPlanetary Data Cafe (OPDC) if someone organized it (anyone can organize and run an OPDC).

If one of us wanted to take point on organizing an OPDC for LPSC, then that might raise some visibility for the PSO TSC, which would be a good thing.

I would be happy to help, but don't have the bandwidth to lead.  @michaelaye might think about leading.  Perhaps for a few hours on the Sunday before the meeting would be better than trying to shoehorn it into M-F?

If you want to help, have ideas to contribute, or want to volunteer to lead, contribute to this Issue.  There is no requirement that we do this.

**Comment by michaelaye** [comment]
I usually arrive on Saturday's at LPSC anyway for the lunar symposium, so I'd be happy to get something together for mid/late Sunday afternoon, right before the ice breaker. Deadline for requesting peripheral space is only in January, but maybe we should get that request in rather earlier than later?

**Comment by AndrewAnnex** [comment]
gahh my airbnb only starts on sunday (what else do I miss on Saturday...), I may try to find an earlier flight but most BWI flights get me into hobby in the late afternoon on sunday IIRC

**Comment by rbeyer** [comment]
Michael, do you plan on captaining an OPDC at LPSC?  If not, then we should close this Issue.  If so, the peripheral space requests were due on Jan 10, but you could still hold one in an impromptu fashion in a hotel lobby somewhere.

**Comment by michaelaye** [comment]
I plan to do something on Sunday before the ice breaker. Missed that extra room deadline, yes, sorry. But either restaurant or bar down stairs could work as well. Am on vacation currently.

**Comment by rbeyer** [comment]
Closing as this topic has been 'overcome by events.'
