### ISSUE TITLE
How deep to the 'requirements' go for TLPs?

### ISSUE THREAD

**Issue by rbeyer** [planetarysoftware/TSC#75]
So, let's assume that we admit something as a TLP that may, itself, have sub-projects (like PlanetaryPy, for instance).  We have 'requirements' that the TLP itself pass (Charter, Code of Conduct, etc.), but what about the sub-projects of TLPs?  How far 'down' do we recurse with the requirements, and how exacting are we about that recursion?

For example, the Astropy project allows projects that are 'functional but unmaintained' to apply to join Astropy, and potentially be admitted if it passes their other criteria.  If PlanetaryPy were to follow suit, then in such a case, a 'functional but unmaintained' project might not have a charter or a modern code of conduct.

I *think* that we only place requirements on the TLP's TC.  If a TLP's TC has a charter that allows for sub-projects, must those sub-projects also have explicit charters, etc., or can it be assumed (by us) that the TLP's charters, etc. apply to them, and it is up to the TLP's TC to deal with compliance and recursion.  If the TLP as a whole (which includes its TC and any sub-projects) does not conform to our requirements, then we address that via our established mechanism.

So in the hypothetical case of PlanetaryPy allowing 'functional but unmaintained' projects as sub-projects, how might that work?  I suggest that PlanetaryPy's charter (or sub-project lifecycle documents) indicate that any projects admitted without explicit 'community' documents, will be assumed to be guided by the 'community' documents of PlanetaryPy itself (or PlanetaryPy establishes a set of 'default' documents that apply to projects without them).  This would allow 'functional but unmaintained' projects to enter PlanetaryPy as sub-projects, but not have a charter, etc., and expect the best.  If the PlanetaryPy TC notices variances of behavior from the 'default' charter, etc. (or receives notice about them via their own published moderation channels), then the PlanetaryPy TC must take action to engage with the sub-project to correct the activity, or delist the sub-project (in the case that such a project is non-responsive).

If this happens and the PlanetaryPy TC deals with this (by bringing the sub-project into alignment or delisting it), then the PlanetaryPy TC remains in 'compliance' with our requirements.  If the PlanetaryPy TC does not deal with these issues, they would (probably) be violating their own charter, and certainly our requirements, and then we can engage with them to help them sort their issues, or the PSO will delist them as a PSO TLP.

Or do we require that sub-projects of TLPs must also have a complete charter, etc.?

**Comment by jessemapel** [comment]
I think that this is up to the TLP. I would recommend simply adopting the TSC documents, but that's up to the TLP. As long as the TLP conforms to our standards, they can manage their sub-projects how they like. The one exception would be if that contradicts the standards they have adopted.

**Comment by rbeyer** [comment]
We talked a lot about this at our telecon today, and I'll admit that immediately prior, I had not reviewed my own very long text above.  Upon re-reading it, I think it is pretty reasonable, and based on our discussion today, I think I'd resolve the 'or' statement/question in the 3rd para to the following:

I think that we (the PSO TSC) only place requirements on the TLP's TC. If a TLP's TC has a charter that allows for sub-projects, then the charter must specify that those sub-projects either have an explicit set of governance documents (charter, code of conduct, etc.) or that the governance documents of the TLP's TC apply to its sub-projects.  If this is not stated in a TLP's charter then there is a a gray area about what rules apply to what.  Including a statement to this effect in the TLP's TC Charter reminds the TLP that the governance model applies to all levels, no matter how nested, of their project.  In any case, is up to the TLP's TC to deal with compliance and recursion. If the TLP as a whole (which includes its TC and any sub-projects) does not conform to our requirements, then we address that via our established mechanism.

And then the 4th and 5th paragraphs as written would apply.

If there is agreement, then these paragraphs (or versions of them) should probably be added to the the Lifecycle document, or maybe the Bootstrap-Policies/Charter document.

**Comment by rbeyer** [comment]
I just reviewed the TSC Charter and the Lifecycle documents.  I don't think anything there needs to be changed.  So I'm going to close this up, as my concern is now resolved.
